# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 16:01
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kipa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versio', models.IntegerField()),
            ],
            options={
                'db_table': 'versio',
            },
        ),
        migrations.CreateModel(
            name='Kisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
                ('aika', models.CharField(blank=True, max_length=255, null=True)),
                ('paikka', models.CharField(blank=True, max_length=255)),
                ('tunnistus', models.BooleanField()),
            ],
            options={
                'db_table': 'kipa_kisa',
                'verbose_name_plural': 'Kisat',
            },
        ),
        migrations.CreateModel(
            name='OsaTehtava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
                ('tyyppi', models.CharField(choices=[('kp', 'kisapisteita'), ('rp', 'raakapisteita'), ('ka', 'kokonaisaika'), ('ala', 'alkuaika ja loppuaika'), ('vk', 'vapaa kaava')], max_length=255)),
                ('kaava', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kipa_osatehtava',
                'ordering': ['nimi'],
                'verbose_name_plural': 'Osatehtavat',
            },
        ),
        migrations.CreateModel(
            name='Parametri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
                ('arvo', models.CharField(max_length=255)),
                ('osa_tehtava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupa.OsaTehtava')),
            ],
            options={
                'db_table': 'kipa_parametri',
                'verbose_name_plural': 'OsaTehtavan paramentrit',
            },
        ),
        migrations.CreateModel(
            name='Sarja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
                ('vartion_maksimikoko', models.IntegerField(blank=True, default=0, null=True)),
                ('vartion_minimikoko', models.IntegerField(blank=True, default=0, null=True)),
                ('tasapiste_teht1', models.IntegerField(blank=True, null=True)),
                ('tasapiste_teht2', models.IntegerField(blank=True, null=True)),
                ('tasapiste_teht3', models.IntegerField(blank=True, null=True)),
                ('kisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupa.Kisa')),
            ],
            options={
                'db_table': 'kipa_sarja',
                'verbose_name_plural': 'Sarjat',
            },
        ),
        migrations.CreateModel(
            name='Syote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arvo', models.CharField(blank=True, max_length=255, null=True)),
                ('tarkistus', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'kipa_syote',
                'verbose_name_plural': 'Syotteet',
            },
        ),
        migrations.CreateModel(
            name='SyoteMaarite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
                ('tyyppi', models.CharField(choices=[('aika', 'aika'), ('piste', 'piste')], max_length=255)),
                ('kali_vihje', models.CharField(blank=True, max_length=255, null=True)),
                ('osa_tehtava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupa.OsaTehtava')),
            ],
            options={
                'db_table': 'kipa_syotemaarite',
                'ordering': ['osa_tehtava', 'nimi'],
                'verbose_name_plural': 'Syotteen maaritteet',
            },
        ),
        migrations.CreateModel(
            name='Tehtava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
                ('lyhenne', models.CharField(max_length=255)),
                ('tehtavaryhma', models.CharField(blank=True, max_length=255)),
                ('tehtavaluokka', models.CharField(blank=True, max_length=255)),
                ('rastikasky', models.TextField(blank=True)),
                ('jarjestysnro', models.IntegerField()),
                ('kaava', models.CharField(max_length=255)),
                ('tarkistettu', models.BooleanField()),
                ('maksimipisteet', models.CharField(max_length=255)),
                ('svirhe', models.BooleanField()),
                ('sarja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupa.Sarja')),
            ],
            options={
                'db_table': 'kipa_tehtava',
                'ordering': ('jarjestysnro',),
                'verbose_name_plural': 'Tehtavat',
            },
        ),
        migrations.CreateModel(
            name='TestausTulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pisteet', models.CharField(max_length=255)),
                ('tehtava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupa.Tehtava')),
            ],
            options={
                'db_table': 'kipa_testaustulos',
                'verbose_name_plural': 'Testattavat tulokset',
            },
        ),
        migrations.CreateModel(
            name='TuomarineuvosTulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pisteet', models.CharField(max_length=255)),
                ('tehtava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupa.Tehtava')),
            ],
            options={
                'db_table': 'kipa_tuomarineuvostulos',
                'verbose_name_plural': 'Tuomarineuvoston tulokset',
            },
        ),
        migrations.CreateModel(
            name='Vartio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.IntegerField()),
                ('nimi', models.CharField(max_length=255)),
                ('piiri', models.CharField(blank=True, max_length=255)),
                ('lippukunta', models.CharField(blank=True, max_length=255)),
                ('puhelinnro', models.CharField(blank=True, max_length=255)),
                ('sahkoposti', models.CharField(blank=True, max_length=255)),
                ('osoite', models.CharField(blank=True, max_length=255)),
                ('keskeyttanyt', models.IntegerField(blank=True, null=True)),
                ('ulkopuolella', models.IntegerField(blank=True, null=True)),
                ('sarja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupa.Sarja')),
            ],
            options={
                'db_table': 'kipa_vartio',
                'ordering': ('nro',),
                'verbose_name_plural': 'Vartiot',
            },
        ),
        migrations.AddField(
            model_name='tuomarineuvostulos',
            name='vartio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupa.Vartio'),
        ),
        migrations.AddField(
            model_name='testaustulos',
            name='vartio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupa.Vartio'),
        ),
        migrations.AddField(
            model_name='syote',
            name='maarite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupa.SyoteMaarite'),
        ),
        migrations.AddField(
            model_name='syote',
            name='vartio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tupa.Vartio'),
        ),
        migrations.AddField(
            model_name='osatehtava',
            name='tehtava',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupa.Tehtava'),
        ),
    ]
