# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupa', '0002_auto_20160407_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisa',
            name='nimi',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
