// JavaScript Document
// Päivitetty 12/2009
// Suomen Partiolaiset: Maija Jauhiainen [Maija.Jauhiainen@partio.fi]

var lpkt = [
  "Enson Partiosiskot ry",
  "Joutsenon Ainotytöt ry",
  "Joutsenon Nuotioveljet ry",
  "Korven Vaeltajat ry",
  "Lappeenrannan Nuotiotytöt ry",
  "Lappeenrannan Suuntaveljet",
  "Lappeenrannan Wallisirkut ry",
  "Lappeenrannan Walliveljet ry",
  "Lappeenrannan Versot",
  "Lappeen Siniset ry",
  "Lappeen Tuulitytöt",
  "Lauritsalan Sinisiskot ry",
  "Lauritsalan Siniveljet ry",
  "Lemin Erävä",
  "Parveilijat ry",
  "Parikkalan Ilvekset ry",
  "Vuorenveikot ry",
  "Raja-Karhut",
  "Rautjärven Rajankävijät ry",
  "Ruokolahden Erätoverit ry",
  "Saaren Kanavakarhut ry",
  "Saimaan Sissit ry",
  "Saimaan Vartiot ry",
  "Savitaipaleen Samoilijat",
  "Taavetin Korpihaukat ry",
  "Taipalsaaren Taivaltajat ry",
  "Tarmontytöt ry",
  "Vuoksen Partioveikot",
  "Ahjopartio ry",
  "Härmän Tähystäjät ry",
  "Alavuden Eräveikot",
  "Evipartio",
  "Het-Partio ry",
  "Ilkan Partiolaiset ry",
  "Isojoen Metsätorrooset",
  "Jurvan Saloveikot ry",
  "Kauhajoen Kytöveikot ry",
  "Kauhavan Erä-Versot ry",
  "Kristiinan Havukat",
  "Kuortaneen Kuismat ry",
  "Kurikan Korvenkävijät ry",
  "Laihian Eräpojat ja Tytöt",
  "Lakeuden Haukat",
  "Lakeuden Kärpät ry",
  "Lakeuden Vartijat ry",
  "Lapuan Kelo-Versot",
  "Lehtimäen Lumikurjet",
  "Maalahden Muurahaiset",
  "Markki-Partio ry",
  "Parran Haltiat ry",
  "Peräseinäjoen Susipartio",
  "Eräkurjet Pietarsaari ry",
  "Sarka-Versot ry",
  "Simpsiön Karhut ry",
  "Simpsiön Siskot ry",
  "Suomi-Weikot",
  "Tasangon Talvikit ry",
  "Vaasan Metsäveikot ry",
  "Vaasan Partiotytöt ry",
  "Vaasan Siniset Partiopojat ry",
  "Vaasan Siniset Partiotytöt ry",
  "Vainion Vesat",
  "Valkeavuoren Urasiskot Ja Veljet",
  "Vähänkyrön Eränkävijät",
  "Ylihärmän Partiolaiset",
  "Ähtärin Eräveikot ry",
  "Anttolan Viiriäiset",
  "Ekin Partio ry",
  "Enonkosken Samoilijat",
  "Hirvi-Partio ry",
  "Joroisten Erätoverit ry",
  "Juvan Partioveikot ry",
  "Jäppilän Eräpartio",
  "Kangaslammin Samoilijat",
  "Kerman Kiertäjät ry",
  "Korpi-Versot ry",
  "Linkki-Partio Lipa ry",
  "Linnavuoren Tähyilijät ry",
  "Metsän Siskot ry",
  "Mikkelin Leiritytöt ry",
  "Mikkelin Muurahaiset ry",
  "Mikkelin Toimenpojat",
  "Mäntyharjun Partiolaiset ry",
  "Nojamaan Neulaset",
  "Norppa-Versot ry",
  "Olavin Partiolaiset",
  "Savonlinnan Mehtä-Versot ry",
  "Otavan Otsot ry",
  "Pertun Tähkäpartio ry",
  "Partio-Unnukka ry",
  "Pieksämäen Metsäsissit ry",
  "Punkaharjun Partiolaiset",
  "Puula-Partio ry",
  "Rantasalmen Ruutanat",
  "Salojen Samoojat",
  "Savon Saukot ry",
  "Savon Sissit ry",
  "Sokkalan Sissit ry",
  "Yöveden Waeltajat ry",
  "Houtskärs Scouter",
  "Flickscoutkåren Korsfararflickorna",
  "Helsingfors KFUK/M Scouter",
  "Helsingfors Scoutkår Spanarna",
  "Iogt Balders Scouter",
  "Scoutkåren MuHö",
  "Munksnäs Flickscouter",
  "Scoutkåren Munksnäs Spejarna",
  "Scoutkåren Nybyggarna",
  "Scoutkåren Spejarna",
  "Sjöscoutkåren Sailors",
  "Sjöscoutkåren Seaboys",
  "Sjöscoutkåren Vikingaflickorna",
  "Sjöscoutkåren Vikingarna",
  "Scoutkåren Fjällfiscarna",
  "Scoutkåren Tre Björkar",
  "Grankulla Scoutkår",
  "Kyrkslätt Scouter",
  "Sjöscoutkåren Stormfågeln",
  "Scoutkåren Ekenäs Skogsvandrare",
  "Ingå Scouter",
  "Hangö Scoutkår",
  "Scoutkåren Fyrbåken",
  "Karis Gossarna",
  "Karis Flickorna",
  "St Jacobs Sjöscouter",
  "Lojo Skogsvandrare",
  "Sjöscoutkåren Havsörnarna",
  "Lovisa Scoutflickor",
  "Lovisa Svenska Boyscouter",
  "Scoutkåren Åfararna",
  "Sjöscoutorganisationen Fribytarna",
  "Östersundom Scouter",
  "Dalsbruks Sjöscouter",
  "Flickscoutkåren Åbo Vildar",
  "KFUM:s Scouter Kamraterna",
  "Pargas Scoutkår Skärgårdsvandrarna",
  "Scoutkåren Pojkarna",
  "Kimito Sjöscouter",
  "St Mikaels Sjöscouter",
  "St Simons Sjöfararna",
  "Tammerfors Spejare",
  "Finströms Sjöscouter",
  "Sjöscoutkåren Spejarna",
  "Scoutkåren Ålandsflickorna",
  "Jakobstads Flickscouter",
  "Jakobstads Fribyggare",
  "Scoutkåren Brobyggarna",
  "Jakobstads Sjöscouter",
  "Korsholms Spejare",
  "Kristinestads Nybyggare",
  "Scoutkåren Korsfararna",
  "Scoutkåren Vasa Korsfararflickor",
  "Pedersörenejdens Korsbärare",
  "Spejarna i Gamlakarleby",
  "Nedervetil Scoutkår Vägvisarna",
  "Södrik Stigfinnare",
  "Scoutkåren Sydvästen",
  "Nykarleby Forsfarare",
  "Närpes Scoutkår",
  "Tempelscouterna",
  "Rekolan Metsäveikot  2",
  "Sjundeå Strömstarar - Siuntion Kosk",
  "Sjöscoutkåren Porkala",
  "Kumlinge Sjöscouter",
  "Öja Sjöscouter",
  "Vårdkasarnas Scouter",
  "Scoutkåren Stormlyktan",
  "Aitolahden Hirvi-Veikot",
  "Aitopartio",
  "Erä-Pirkot",
  "Forssan Tornitulet ja Tornihaukat",
  "Harjun Pojat ry",
  "Harjun Veikot",
  "Harjusiskot",
  "Hauhon Partiolaiset ry",
  "Hervannan Hukat",
  "Hiipan Pojat",
  "Humppilan Ilvespojat",
  "Hämeen Haka-Versot",
  "Hämeenkyrön Hälläpyörät",
  "Hämeenlinnan Metsänkävijät",
  "Hämeenlinnan Pirteät",
  "Partiolippukunta Liekkitytöt ry",
  "Hämeen Samoilijat",
  "Härmälän Haukat",
  "Härmälän Ilvestytöt ry",
  "Ikaalisten Korpi-Kotkat",
  "Ikaalisten Poppeliversot",
  "Jaakon Samoojat",
  "Jaarlin Pojat ry",
  "Janakkalan Ilvekset ry",
  "Jokioisten Korvenkävijät",
  "Juupajoen Eräpartio",
  "Kalevan Karhut",
  "Kalevan Suuntatytöt ry",
  "Kalvolan Katajasiskot",
  "Kalvolan Olavinpojat",
  "Kanavan Vartijat",
  "Karkun Samoojat",
  "Kaskenkaatajat",
  "Kaukapartio",
  "Kihniön Katajaiset",
  "Kivekkäät",
  "Koijärven Kurjet",
  "Kostian Kahlaajat",
  "Kuhmalahden Lieskapartio",
  "Kuhmoisten Eränkävijät",
  "Kuoreveden Kotkat",
  "Kyröskosken Karhunpojat",
  "Längelmäen Partiolaiset",
  "Lentävän Samoojat",
  "Kurun Kontiot",
  "Kyynärön Kiertäjät",
  "Messukylän Metsäpojat",
  "Messukylän Metsätytöt ry",
  "Mouhijärven Metsot",
  "Multisillan Katajat",
  "Mäntänvuoren Partiolaiset",
  "Niihaman Saukot",
  "Nokian Eräveikot",
  "Nokian Partiotytöt ry",
  "Nummen Eränkävijät",
  "Näsin Tytöt ry",
  "Oriveden Eräsiskot",
  "Oriveden Eräsissit",
  "Otsolan Pojat ja Tytöt",
  "Parolan Eräveikot",
  "Pirkan-Pojat",
  "Pirkkalan Pirkot",
  "Pirkkalan Sotkapojat",
  "Punkalaitumen Metsänkävijät",
  "Soihdunkantajat",
  "Roineen Tytöt",
  "Sahalahden Sinisudet ry",
  "Sata-Hämeen Vasamat",
  "Stoolin Partiolaiset",
  "Suodenniemen Suonkiertäjät",
  "Sääksmäen Nuotiopojat",
  "Tammelan Metsänkävijät",
  "Tammero ry",
  "Tammer-Pojat",
  "Tammer-Tytöt",
  "Tampereen Eräkarhut",
  "Tampereen Eräpojat",
  "Tampereen Kotkat",
  "Tampereen Lokit",
  "Tampereen Pajapojat",
  "Tampereen Suuntaveljet",
  "Tampereen Versot",
  "Tarjanteen Tallustajat ry",
  "Teiska-Partio",
  "Tervakosken Tervakset",
  "Tesoman Sinisiskot",
  "Toijalan Eräveikot",
  "Torisevan Tarpojat ry",
  "Tuuloksen Tulikourat",
  "Tyrvään Metsänpojat",
  "Urjan Varstat ry",
  "Valkeakosken Koski-Versot",
  "Valkeakosken Korvenkävijät ry",
  "Valkeakosken Venlat",
  "Vammalan Nuotiosiskot",
  "Viialan Metsänkävijät",
  "Wanajan Ilves",
  "Vehmaisten Siniveikot",
  "Vesilahden Valkohännät",
  "Viinikan Siniset",
  "Viinikan Sinitytöt",
  "Ylöjärven Otava ry",
  "Ylöjärven Viittaveljet",
  "Hyryn Korpisudet ry",
  "Kainuun Katajat ry",
  "Kajaanin Eränkävijät ry",
  "Kajaanin Korvenpojat ry",
  "Kuhmon Siniset ry",
  "Saukon Samoojat ry",
  "Turjankävijät ry",
  "Vaalan Metsänkävijät ry",
  "Vaarojen Samoojat",
  "Vaarojen Vaeltajat ry",
  "Vuokatin Vaeltajat ry",
  "Alavieskan Partioveikot ry",
  "Haapajärven Eräpartio ry",
  "Halkokariset ry",
  "Halsuan Suohaukat",
  "Himangan Nuotioveljet",
  "Karin Katajaiset",
  "Kannuksen Korvenkävijät ry",
  "Kaustisen Kallionkoluajat ry",
  "Kokkolan Suuntaveljet",
  "Kokko-Pojat ry",
  "Kokkolan Vaeltajat ry",
  "Kokko-Tytöt ry",
  "Kälviän Metsäveikot ry",
  "Lestijärven Lepakot",
  "Liungilan Eränkävijät ry",
  "Lohtajan Teiskuveljet ry",
  "Nivalan Partio",
  "Perhon Pilvenveikot",
  "Raudaskylän Ristilukit",
  "Reisjärven Hongankolistajat",
  "Salmen Samoajat ry",
  "Sievin Samoojat ry",
  "Toho-Taivaltajat",
  "Tulikokot",
  "Ullavan Eräpojat",
  "Vetelin Koskenkävijät ry",
  "Viessojat ry",
  "Vääräjoen Vartijat",
  "Halssilan Haukat ry",
  "Ilvespartio ry",
  "Huhtapartio ry",
  "Joutsan Jousipartio ry",
  "Jyväskylän Eräpartio",
  "Jyväskylän Metsänkävijät ry",
  "Jyväskylän Suuntaveljet",
  "Jyväskylän Versot ry",
  "Jämsän Leirisudet ry",
  "Jämsän Jokipartio ry",
  "Kaipolan Tiirat ry",
  "Kannon Veikot",
  "Karstulan Korpi-Karstut",
  "Keljon Kävijät ry",
  "Kinnulan Korpisudet ry",
  "Kuokkalan Vetehiset ry",
  "Korpilahden Korvensamoojat",
  "Keuruversot",
  "Kortepartio ry",
  "Koskipartio",
  "Kulhan Kulkijat ry",
  "Kuuhankaset ry",
  "Kuuvalon Vaeltajat ry",
  "Kyypartio ry",
  "Lievestuoreen Partiopojat ry",
  "Lievestuoreen Tuulentytöt ry",
  "Muuratpartio ry",
  "Mäkipartio ry",
  "Palokan Partiolaiset ry",
  "Partiosiskot ry",
  "Pihkapartio ry",
  "Pihtiputaan Partiolaiset ry",
  "Reippaat Pojat ry",
  "Reippaat Pojat ry",
  "Reippaat Tytöt ry",
  "Saarijärven Saloveikot ry",
  "Siniset Samoojat ry",
  "Sumiaisten Samoojat",
  "Suolahden Versot",
  "Suopartio ry",
  "Säynätsalon Päijännepartio ry",
  "Keurusseudun Partiolaiset ry",
  "Tervaspartio",
  "Tikkakosken Partiolaiset ry",
  "Toivakan Lepinkäiset ry",
  "Katajaiset ja Tomerat ry",
  "Vaajan Valppaat ry",
  "Äänekosken Versot",
  "Vihtavuoren Visaiset ry",
  "Viitasaaren Partiolaiset ry",
  "Äänekosken Metsäveikot",
  "Äänetytöt ry",
  "Anjalan Eräsiskot",
  "Elimäen Metsäsudet",
  "Elimäen Metsäveikot",
  "Hakun Partio",
  "Haminan Päivänpojat",
  "Haminan Rantarillit ry",
  "Inkeroisten Eräveikot",
  "Jaalan Jalopeurat",
  "Karhulan Kanttarellit ry",
  "Karhulan Korvenkävijät",
  "Kelo-Versot ry",
  "Korian Kivitaskut",
  "Kotkan Meriversot",
  "Kouvolan Metsäveikot ry",
  "Kouvolan Nuotio-Sissit",
  "Kouvolan Sini-Veikot ry",
  "Kouvolan Tyttöpartio ry",
  "Kuusankosken Metsänkävijät ry",
  "Kuusankosken Partiotytöt ry",
  "Kymen Rannanpojat",
  "Kymenrannan Tytöt ry",
  "Langinkosken Samoojat",
  "Maakotkat ry",
  "Merihaukat ry",
  "Merituikut ry",
  "Myllykosken Koskikarat ry",
  "Myllykosken Koskipojat",
  "Elimäen Peipposet ry",
  "Pyhtään Korpisudet",
  "Rajan Reippaat ry",
  "Kouvolan Salpasirkat ry",
  "Utin Pilvenveikot",
  "Valkealan Kolmisoihtu",
  "Nuotio-Vehkat ry",
  "Inarin Tunturisudet ry",
  "Kallin Kanervat ry",
  "Karun Sirkut ja Eräveljet",
  "Kemijärven Tunturitytöt ja Pojat",
  "Keminmaan Kivekkäät",
  "Kielaat ry",
  "Kemin Versot ry",
  "Kemin Suuntaveljet ry",
  "Keron Kiertäjät",
  "Kiirunapartio",
  "Kitkankiertäjät",
  "Korvatunturin Kävijät",
  "Kuivaniemen Norpat",
  "Lapin Kiehiset ja Kivekkäät ry",
  "Lapin Samoilijat",
  "Mellan Kiipijät",
  "Muonion Susipirkat",
  "Njalat",
  "Napapiirin Pojat ry",
  "Napapiirin Tytöt",
  "Kätkän Kävijät ry",
  "Pellon Pailakat",
  "Pellon Väyläveikot",
  "Pohjan Tytöt ja Sissit",
  "Pohjolan Tytöt ry",
  "Sallan Erauspojat",
  "Seitapartio",
  "Simon Kuutit",
  "Totto-Partio",
  "Veitsiluodon Metsänkävijät",
  "Ylläs-Partio",
  "Iljalan Eränkävijät ry",
  "Joensuun Eräsissit ry",
  "Joensuun Haka-Versot ry",
  "Joensuun Metsänkävijät ry",
  "Jokisuun Kipparit ry",
  "Juuan Kiitäjät ry",
  "Karjalan Eräversot",
  "Karjalan Korvenkävijät KKK ry",
  "Karjalan Näreennakertajat ry",
  "Karjalan Tytöt ry",
  "Kesälahden Siniveikot ry",
  "Kiihtelyksen Nuotiosissit ry",
  "Kiteen Karhu-Pojat ry",
  "Kiteen Rajasamoojat ry",
  "Kaiskun-Kävijät ry",
  "Korpipuolukat ry",
  "Nurmeksen Partiolaiset ry",
  "Liperin Kokkoveikot ry",
  "Noljakan Niemenkiertäjät ry",
  "Outokummun Kipinät ja Kummun Eräveik",
  "Pielisensuun Samoojat ry",
  "Pogostan Pojat",
  "Polvijärven Päreenpolttajat ry",
  "Pyhäselän Eräsotkat ry",
  "Rantakylän Rämpijät ry",
  "Tikkamäen Tikkatytöt ry",
  "Tohmajärven Metsänsamoilijat ry",
  "Vaaran Veljet ja Siskot ry",
  "Vaarojen Siskot ja Veikot ry",
  "Valtimon Partiolaiset ry",
  "Värtsin Takojat ry",
  "Haapaversot",
  "Hanhikiven Kiertäjät",
  "Illinkiertäjät ry",
  "Keskipisteen Kairankävijät",
  "Kelopojat ry",
  "Kiimingin Virkut ry",
  "Kokkopartio",
  "Koskenkotkat ry",
  "Koskiveikot",
  "Kuusamon Tunturisiskot ja Veikot ry",
  "Käylän Kiehiset ry",
  "Limingan Niittykärpät",
  "Merijärven Tervanpolttajat",
  "Muhoksen Metsänkävijät ry",
  "Tyrnävän Mustavarikset ry",
  "Oulun Metsänkävijät ry",
  "Pohjolan Pirteät ry",
  "Oulunsalon Norret",
  "Oulun Suuntaveljet ry",
  "Oulun Valppaat ry",
  "Oulun Pihka-Versot ry",
  "Pateniemen Polunpolkijat ry",
  "Pohjan Ilves",
  "Pohjan Veikot",
  "Putaan Vilkkaat ry",
  "Pyhännän Kairan Kotkat ry",
  "Pudasjärven Mesikämmenet",
  "Merituuli ry",
  "Raahen Teräs-Versot",
  "Rämeen Rämpijät",
  "Ruukin Samoojat ry",
  "Saloisten Sirkat ja Sudet ry",
  "Haapaveden Salopartio ry",
  "Samposet ry",
  "Soopa ry",
  "Suotarpojat ry",
  "Suomuuraimet ja Sutipurikat",
  "Tervapartio ry",
  "Tervastuli ry",
  "Toimarit ry",
  "Vihannin Vehkat ry",
  "Ylikiimingin Jänkävartiot",
  "Alapitkän Metsämyyrät ry",
  "Iisalmen Korventytöt ry",
  "Iisalmen Korvenveikot ry",
  "Järvisissit ry",
  "Kaavin Kiehiset ry",
  "Kallan Kontiot ry",
  "Kallan Tiirat ry",
  "Kallan Tytöt ry",
  "Karttulan Kannonkiertäjät ry",
  "Keiteleen Saukot ry",
  "Kinahmin Kiipijät ry",
  "Kiuru-Partio ry",
  "Juankosken Korpikulkurit ry",
  "Kuilun Kulkijat ry",
  "Kuopion Metsäpojat ry",
  "Kuopion Opiskelijapartiolaiset ry",
  "Lapinlahden Siniveikot ry",
  "Leijona Tytöt ry",
  "Lepikon Tarpojat ry",
  "Soisalon Samoilijat ry",
  "Länsirannan Partiolaiset ry",
  "Männistön Nuotta ry",
  "Puijon Pojat",
  "Puijon Pakertajat ry",
  "Rautalammin Rautiaiset ry",
  "Riistaveden Vaarunvartijat ry",
  "Sonkapartio ry",
  "Sutelan Hukat ry",
  "Suonenjoen Sirkut ja Sotkat ry",
  "Maaningan Maahiset ry",
  "Talaspartio ry",
  "Tervon Tervaspartio ry",
  "Tuusniemen Tuohiset",
  "Vehmerin Vaeltajat ry",
  "Vesannon Partiolaiset ry",
  "Aarnikarhut",
  "Aarnivalkeat",
  "Alppikauriit ry",
  "Alppikotkat",
  "Espoon Metsänkävijät",
  "Eiran Vihervillit ry",
  "Helsingin Eräkaverit",
  "Haagan Eräveikot",
  "Haagan Sirkut",
  "Haapakertut",
  "Hakasiskot ry",
  "Helsingin Erä-Leijonat ry",
  "Vuorenhaltiat ry",
  "Hanseaten",
  "Harmaat Karhut",
  "Haukka-Veikot",
  "Haukkavuoren Haltiat",
  "Helsingin Hakatytöt ry",
  "Helsingin Kalevan Pojat",
  "Helsingin Kalevan Tytöt ry",
  "Helsingin Kotkat ry",
  "Helsingin Metsänkävijät",
  "Helsingin Metsänpojat",
  "Helsingin Sinihaukat",
  "Helsingin Siniset",
  "Järvihaukat",
  "Helsingin Versoveikot ja Siskot",
  "Hespartto ry",
  "Hippiäiset",
  "Hipsut ry",
  "Jyrin Sissit",
  "Ilvesveikot",
  "Ilvesveikot",
  "Espoon Suuntaveljet",
  "Kaarnapartio",
  "Huipunvaltaajat",
  "Kaivokselan Delfiinit",
  "Kaskenpolttajat",
  "Kallion Kaiut",
  "Keronkävijät ry",
  "Kappelitytöt",
  "Kara-Karhut",
  "Karhu-Veikot",
  "Kartanopartio ry",
  "Kaskipartio",
  "Kauka-Kuutit ry",
  "Kehäpartio ry",
  "Kelotytöt",
  "Kelovartijat",
  "Kirisiskot ry",
  "Koivusissit ry",
  "Kontutytöt",
  "Korson Honkaveljet ry",
  "Korven Koukkaajat",
  "Koskenhaltiat ry",
  "Marjaniemen Suuntaveljet ry",
  "Koudat ry",
  "Kuksat ry",
  "Mankkaan Eräsudet",
  "Kulosaaren Meripartio",
  "NMKY:n Rastipartio",
  "Hakkipartio",
  "Käpytytöt ry",
  "Laajalahden Eräveikot",
  "Lauttapartio",
  "Lauttasaaren Lainepartio ry",
  "Lauttasaaren Luotsitytöt ry",
  "Leppäpirkot",
  "Lounapartio ry",
  "Laulavat Soihdut",
  "Maahiset ry",
  "Mastonvartijat",
  "Merimetsot ry",
  "Helsingin Kiehiset",
  "Meritähdet ry",
  "Metsolan Pojat ry",
  "Mesikämmenet",
  "Mustat Veljet ry",
  "Muuttolinnut ry",
  "Myllymarit ry",
  "Myyrpartio ry",
  "Navigatores",
  "NMKY:n Katajaiset",
  "Olarin Eräkotkat ry",
  "Niipperin Nuolihaukat",
  "Oravanmarjat",
  "Susiveikot ry",
  "Oulunkylän Virkut ry",
  "Otavaeltajat ry",
  "Pakinrinkat ry",
  "Helsingin Suuntaveljet",
  "Pitkäjärven Vaeltajat",
  "Piisamit",
  "Partiolippukunta Viikin Vesikot",
  "Puropartio",
  "Pursitytöt",
  "Pyhän Laurin Ritarit (PäPa)",
  "Rantasipit ry",
  "Rekolan Metsäsiskot ry",
  "Rekolan Metsäveikot",
  "Siniritarit ry",
  "Saharan Sissit",
  "Majakka",
  "Erämetsot",
  "Simometsot",
  "Sinivuoren Tytöt",
  "Solmutytöt ja Portimon Pojat ry",
  "Sopulit",
  "Suomenlinnan Merisudet ry",
  "Suosirrit",
  "Helsingin Erä-Majavat",
  "Vuoren Valppaat",
  "Tammisalon Metsänkävijät",
  "Tammitytöt",
  "Tapiolan Eräpojat",
  "Tapiolan Metsänkävijät",
  "Tellervoiset ry",
  "Tikkurilan Siniset ry",
  "Toimen Pojat ry",
  "Toimen Tytöt ry",
  "Tuikku-Tytöt ry",
  "Leppävaaran Korvenkävijät",
  "Sisulippukunta Onnikit",
  "Töölön Nuotioveikot",
  "Töölön Siniset ry",
  "Töölön Tähystäjät ry",
  "Vaaran Vaeltajat ry",
  "Kulman Kiertäjät ry",
  "Vantaan Metsänkävijät ry",
  "Vartiovuoren Pojat ry",
  "Vartiovuoren Tytöt ry",
  "Vuosaaren Pesukarhut",
  "Viestitytöt ry",
  "Viipurin Metsänkävijät",
  "Vuokot ry",
  "Vuosaaren Vesipääskyt ry",
  "Yrjänäiset ry",
  "Kolmiapila-Treklöver",
  "Jeanne dArc ry",
  "Olarinmäen Samoojat",
  "Suvelan Samoojat",
  "Teepakki",
  "Kivenlahden Piilevät",
  "Kontupojat ry",
  "Partiolippukunta Tavastit ry",
  "Fratello",
  "Kurkisuon Rusakot",
  "Viherlaakson Peurat ry",
  "Karhunvartijat ry",
  "Katajanokan Karhunkaatajat ry",
  "Vantaan Jokiversot",
  "Kilon Kipinät",
  "Aurinkovuoren Vartijat ry",
  "Harjunalustan Siniveljet",
  "Hirviveikot ry",
  "Hollolan Hirvenhiihtäjät ry",
  "Koskenlaskijat ry",
  "Kruunun Savu",
  "Kuikkavuoren Pojat ry",
  "Kymen Kotkat",
  "Kymen Vartiot ry",
  "Kärkölän Kärpät ry",
  "Lahden Ilvesveikot ry",
  "Lahden Katajaiset",
  "Lahden Partiosissit",
  "Lahden Siniset ry",
  "Lahden Suuntaveljet",
  "Lahden Versot ry",
  "Launeen Lähdesiskot ry",
  "Lähteen Vartijat ry",
  "Myllykylän Harjuvuokot ry",
  "Myrskylinnut ry",
  "Nastapartio ry",
  "Padaspartio ry",
  "Orimattilan Samoilijat ry",
  "Partioseniorit",
  "Pirjetan Partio ry",
  "Lammin Evonkävijät ry",
  "Puuha-Marit ry",
  "Rautvuoren Vartijat ry",
  "Riihimäen Eräpojat ry",
  "Riihimäen Erätytöt ry",
  "Riihipääskyt ry",
  "Ryttylän Eräveikot ry",
  "Santamäen Palokärjet ry",
  "Sinisissit ry",
  "Sysi-Partio",
  "Joutjärven Tapulitytöt ry",
  "Tiirismaan Tähystäjät",
  "Ahlaisten Ankkurit ry",
  "Euran Peurat ry",
  "Harjavallan Pirkat",
  "Honkahukat ry",
  "Huittisten Eränkävijät ry",
  "Jokilaakson Ravut ry",
  "Jämijärven Miilunvartijat ry",
  "Kankaanpään Korpiveikot",
  "Karimo ry",
  "Karvian Majavapartio ry",
  "Keikyän Korvenkävijät ry",
  "Kiikan Leiripeikot",
  "Kiikoisten Partiopojat ry",
  "Kiukaisten Metsäveikot ry",
  "Kopardit ry",
  "Käppäräpartio ry",
  "Lallin Partio",
  "Luvian Loukke ry",
  "Meri-Porin Partio ry",
  "Mesikäpälät ry",
  "Myrskypojat ry",
  "Nakkilan Partiolaiset ry",
  "Narvin Pojat",
  "Narvin Tytöt ry",
  "Ouran Partiolaiset ry",
  "Kipinäpartio ry",
  "Pomarkun Polunkävijät ry",
  "Porin Nuotiopojat ry",
  "Porin Tertut ry",
  "Porin Tulitikut ry",
  "Porin Versot ry",
  "Pääskyparvi ry",
  "Rauman Partiotytöt ry",
  "Rauman Sinermot ry",
  "Ruoripojat ry",
  "Saaren Kiertäjät ry",
  "Säkylän Partio ry",
  "Tasalam Boja ry",
  "Teljän Partio ry",
  "Teljän Tuikkeet ry",
  "Ulvilan Eräpojat ry",
  "Ulvilan Erätytöt ry",
  "Vampulan Varpuspartio ry",
  "Vesipeikot ry",
  "Väinän Vartijat ry",
  "Artjärven Eränkävijät",
  "Eräkamut ry",
  "Hangon Meriversot",
  "Harjunkiipijät",
  "Hiiden Hittavaiset ry",
  "Hiistulen Tytöt ry",
  "Hyökäpartio",
  "Hyvinkään Metsätytöt ry",
  "Hyvinkään Miilupartio ry",
  "Hyvinkään Nummenpojat",
  "Hyvinkään Suuntaveljet",
  "Inkoon Samoilijat",
  "Jokipartio ry",
  "Jukolan Veljet ja Siskot",
  "Järvenpään Arkki-Versot ry",
  "Kiehiset ry",
  "Järvenpään Metsänkävijät ry",
  "Karkkilan Partiosiskot ry",
  "Karkkilan Partioveikot ry",
  "Keravan Korvenpojat",
  "Keravan Suuntaveljet",
  "Kirkkonummen Metsänkävijät",
  "Kirkkonummen Metsäntytöt",
  "Linnajoen Partiolaiset",
  "Lohjan Eräveikot ry",
  "Lohjan Nummitytöt",
  "Lohjan Nummitytöt",
  "Lohjanharjun Vartijat",
  "Ankkuripartio ry",
  "Kirnun Kiertäjät",
  "Mäntsälän Metsäkävyt",
  "Nummen Samoojat",
  "Upinniemen Merisissit ry",
  "Pornaisten Solmu ry",
  "Pukkilan Partio",
  "Polaris",
  "Rajamäen Metsänkävijät",
  "Savion Suvisiskot",
  "Klapaset ry",
  "Sipoon Hukat",
  "Siuntion Linnanvoudit",
  "Virkkalan Tulentekijät",
  "Tuuspartio",
  "Valontuojat",
  "Vivamon Virittäjät",
  "Veikkolan Eräveikot ja -haltiat ry",
  "Vihdin Polunlöytäjät",
  "Ahertajat ry",
  "Alastaron Jyväset",
  "Auran Eräkurjet ry",
  "Auran Tytöt ry",
  "Auran Tähti Pojat",
  "Hakkistytöt ry",
  "Halikon Siniset ry",
  "Henrikin Tapulitytöt ry",
  "Hirvensalon Eräpojat ry",
  "Ilpoisten Vuorenkävijät ry",
  "Jokikylän Pojat",
  "Kaarinan Korpiklaani ry",
  "Kaarinan Ristiritarit ry",
  "Kaarinan Sädetytöt ry",
  "Kaarinan Sädetytöt ry",
  "Kakskerran Kaksoispiste ry",
  "Kiikalan Kelopartio",
  "Kiskon Kupariset",
  "Koroisten Ritarit ry",
  "Koroisten Sarpiot ry",
  "Kolkankävijät",
  "Kosken Kerkät",
  "Kupittaan Henrikinpojat ry",
  "Kustavin Merikotkat ry",
  "Kuusiston Linnanyrjänät ry",
  "Kuusenkävyt ry",
  "Kyrön Kiurut ja Kokot ry",
  "Laitilan Eräsissit",
  "Laitilan Lumikit ry",
  "Leirisiskot",
  "Liedon Eränkävijät",
  "Littoisten Pirtapiiat ry",
  "Loimaan Nuotioloimut",
  "Loimaan Saviset",
  "Lokalahden Erälokit",
  "Louhen-Tytöt ry",
  "Lähteen Tytöt ja Pojat",
  "Lätynkääntäjät ry",
  "Maarian Kämmekät ry",
  "Maarian Tähkät ry",
  "Marjatat ja Mikon Pojat",
  "Maskun Hemmingin Tyttäret ja Pojat",
  "Marttilan Martit",
  "Mynämäen Maahiset ry",
  "Mellilän Menninkäiset ry",
  "Merenkävijät",
  "Merimaskun Reimarit ry",
  "Mietoisten Kolopuutintit ry",
  "Mikaelin Sinikellot ry",
  "Mustavuoren Sissit ry",
  "Muurlan Muurahaiset",
  "Naantalin Naakat",
  "Naantalin Siniset",
  "Nousiaisten Henrikin Lippukunta",
  "Nuotiotytöt ry",
  "Kairankiertäjät",
  "Turun Meripeikot",
  "Partio-Puhurit ry",
  "Paraisten Merikotkat ry",
  "Pyhän Laurin Ritarit PLR ry",
  "Perttelin Piketit ry",
  "Piikkiön Tammipartio ry",
  "Puhurin Pojat ry",
  "Pöytyän Pöllöt ry",
  "Pyhärannan Korpiankkurit",
  "Raision KilliNallit",
  "RajakivenKiertäjät ry",
  "Rantakaarinat ry",
  "Ruskon Maunun-Partio",
  "Rymättylän Märssyvahdit ry",
  "Salon Eränkävijät",
  "Salon Leiriveikot",
  "Saloversot",
  "Suomusjärven Mesoliitit",
  "Sauvojapojat ry",
  "Särkisalon Simpukat",
  "Tavastin Liljat ry",
  "Tarvan Tapiot",
  "Toivon Erätytöt",
  "Tornikotkat ry",
  "Tornipääskyt ry",
  "Taivassalon Tupshaukat ry",
  "Tuulihaukat ry",
  "Turun Eränkävijät",
  "Turun Metsänkävijät",
  "Turun Mikaelin Siniset ry",
  "Turun Partio-Sissit ry",
  "Turun Sinikotkat ry",
  "Turun Suuntaveljet",
  "Turun Versot",
  "Turun Tähti-Tytöt ry",
  "Uudenkaupungin Merihait ry",
  "Vaakun Vartijat ry",
  "Vahdon Korvenkävijät ry",
  "Varsinais-Suomen Samoilijat",
  "Vehmaan Lustaset ry",
  "Yläneen Korpijunkkarit ry",
  "Ypäjän Eränkävijät",
  "Nordsjö Skogsriddare",
  "Wasa Fyrvaktare",
  "Petosen Polunetsijät ry",
  "Porvoon Polunlöytäjät",
  "Tervolan Jatulitytöt ja Pojat",
  "Ylämyllyn Samoojat ry",
  "Kellokontiot Keko",
  "Soinin Suopöllöt",
  "Kullaan Kuusipeurat ry",
  "Kyöpelin Kiertäjät",
  "Siikaisten Karhunveikot",
  "Vanajan Metsänkävijät",
  "Vimpelin Villikehrät ry",
  "Yli-Iin Revontulet",
  "Kyyhkypartio ry",
  "Ylämaan Kivisissit",
  "Partiolippukunta Eräveijarit ry",
  "Kainuun Revontulet ry",
  "Kuninkaantien Kipinät",
  "Miehikkälän Metsänkävijät",
  "Kuopion Eräversot ry",
  "Lavian Eränkävijät ry",
  "Frikyrkoscoutkåren Stigfinnarna",
  "Porvoon Metsänkävijät ry",
  "Sipoonkorven Haltiat ry",
  "Nuuksion Eräkarhut ry",
  "Puskapartiolaiset ry",
  "Ukonharjun Samoojat ry",
  "Koskenpään Koskikarat",
  "Lahelan Palokärjet ry",
  "Pielisen Partiolaiset ry",
  "Föreningen Navigator rf",
  "Sammatin Solmut ry",
  "Lapinjärven Peurat ry",
  "Sammalisen Samoilijat",
  "Kuopion Kurjenmiekat ry",
  "Espoon Leppäversot",
  "Kantvikin Tulentekijät ry",
  "Martin Partio ry",
  "Lakeuden Eräpartio ry",
  "Partio-Kotkat ry",
  "Iisalmen Korventytöt ry, PoSaPa",
  "Juankosken Korpikulkurit ry, PoSaPa",
  "Järvisissit ry, PoSaPa",
  "Kaavin Kiehiset ry, PoSaPa",
  "Kallan Kontiot ry, PoSaPa",
  "Kallan Tytöt ry, PoSaPa",
  "Karttulan Kannonkiertäjät ry, PoSaPa",
  "Kinahmin Kiipijät ry, PoSaPa",
  "Kiuru-Partio ry, PoSaPa",
  "Kuilun Kulkijat ry, PoSaPa",
  "Kuopion Kurjenmiekat ry, PoSaPa",
  "Kuopion Metsäpojat ry, PoSaPa",
  "Kuopion Opiskelijapartiol. ry, PoSaP",
  "Lapinlahden Siniveikot ry, PoSaPa",
  "Leijona Tytöt ry, PoSaPa",
  "Lepikon Tarpojat ry, PoSaPa",
  "Länsirannan Partiolaiset ry, PoSaPa",
  "Männistön Nuotta ry, PoSaPa",
  "Puijon Pakertajat ry, PoSaPa",
  "Rautalammin Rautiaiset ry, PoSaPa",
  "Riistaveden Vaarunvartijat ry, PoSaP",
  "Soisalon Samoilijat ry, PoSaPa",
  "Sonkapartio ry, PoSaPa",
  "Suonenjoen Sirkut ja Sotkat ry, PoSa",
  "Sutelan Hukat ry, PoSaPa",
  "Talaspartio ry, PoSaPa",
  "Vehmerin Vaeltajat ry, PoSaPa",
  "Vesannon Partiolaiset ry, PoSaPa",
  "Iisalmen Korvenveikot ry, PoSaPa",
  "Puijon Pojat, PoSaPa",
  "Tervaksentekijät",
  "Haarajoen Törmän Tähystäjät",
  "Keiteleen Saukot ry, PoSaPa",
  "Petosen Polunetsijät ry, PoSaPa",
  "Tuusniemen Tuohiset, PoSaPa",
  "Lepsämän Partio",
  "Aviapartio",
];

var piirit = [
  "Etelä-Karjalan Partiolaiset ry",
  "Pohjanmaan Partiolaiset ry",
  "Järvi-Suomen Partiolaiset ry",
  "Etelä-Savon Partiolaiset ry",
  "Finlands Svenska Scouter r.f.",
  "Uudenmaan Partiopiiri ry",
  "Hämeen Partiolaiset ry",
  "Kainuun Partiolaiset ry",
  "Keski-Suomen Partiolaiset ry",
  "Kymenlaakson Partiopiiri ry",
  "Lapin Partiolaiset ry",
  "Pohjois-Karjalan Partiolaiset ry",
  "Pohjois-Savon Partiolaiset ry",
  "Pääkaupunkiseudun Partiolaiset ry",
  "Salpausselän Partiolaiset ry",
  "Lounais-Suomen Partiopiiri ry",
];
