#!/bin/bash

set -e

docker_compose="docker-compose --file docker-compose.yml"

function cleanup() {
  $docker_compose down
}

function die() {
    echo $@
    exit 1
}

trap cleanup EXIT

$docker_compose build
$docker_compose up -d
$docker_compose run web './manage.py' test
