#!/bin/bash

chown www-data /opt/kipa/web
chown www-data /opt/kipa/web/tupa.db
ln -s /opt/kipa/web/media /var/www/kipamedia

apacheConf=/etc/apache2/httpd.conf

echo '<location "/kipa/">' >> ${apacheConf}
echo '   SetHandler python-program' >> ${apacheConf}
echo '   PythonHandler django.core.handlers.modpython' >> ${apacheConf}
echo '   SetEnv DJANGO_SETTINGS_MODULE web.settings' >> ${apacheConf}
echo '    PythonDebug On' >> ${apacheConf}
echo "    PythonPath \"['/opt/kipa'] + sys.path\"" >> ${apacheConf}
echo '</Location>' >> ${apacheConf}

/etc/init.d/apache2 restart

