-- ================================================================================
--   mysql SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   mysql
--   Generated at:      Sun Dec 21 12:04:43 2008
--   Input Files:       tietokanta.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Dec 21 12:04:42 2008
--     Input Files:       tietokanta.dia



-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Dec 21 12:04:42 2008
--     Input Files:       tietokanta.dia




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Dec 21 12:04:42 2008
--     Input Files:       tietokanta.dia



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Dec 21 12:04:42 2008
--     Input Files:       tietokanta.dia

 drop table if exists kisa ;
 drop table if exists sarja ;
 drop table if exists tehtava ;
 drop table if exists tekia ;
 drop table if exists vartio ;
 drop table if exists rasti ;
 drop table if exists rastimiehet ;
 drop table if exists rasti_tehtava_liitos ;
 drop table if exists raakatulos ;
 drop table if exists lopputulos ;
 drop table if exists syote ;
 drop table if exists arvosteluperuste ;
 drop table if exists osanottaja ;
 drop table if exists allergia ;
 drop table if exists sarja_rasti_liitos ;
 drop table if exists rasti_vartio_liitos ;


-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Dec 21 12:04:42 2008
--     Input Files:       tietokanta.dia


-- kisa
create table kisa (
  id                         int unsigned auto_increment not null,
  nimi                       varchar(255) not null,
  aika                       date,
  paikka                     varchar(255),
  constraint pk_Kisa primary key (id)
) ;

-- sarja
create table sarja (
  id                         int unsigned auto_increment not null,
  nimi                       varchar(255) not null,
  maksimipisteet             float(4,2),
  vartion_maksimikoko        int unsigned,
  vartion_minimikoko         int unsigned,
  kisa_id                    int unsigned not null,
  constraint pk_Sarja primary key (id)
) ;

-- tehtava
create table tehtava (
  id                         int unsigned auto_increment not null,
  nimi                       varchar(255) not null,
  maksimipisteet             float(4,2),
  tehtavaryhma               varchar(255),
  rastikasky                 text,
  jarjestysnro               int unsigned,
  kaava                      varchar(255),
  constraint pk_Tehtava primary key (id)
) ;

-- tekia
create table tekia (
  id                         int unsigned auto_increment not null,
  nimi                       varchar(255) not null,
  tehtava                    varchar(255),
  puhelinnumero              varchar(255),
  kisa_id                    int unsigned,
  constraint pk_Tekia primary key (id)
) ;

-- vartio
create table vartio (
  numero                     int unsigned auto_increment not null,
  nimi                       varchar(255) not null,
  kisa_id                    int unsigned,
  sarja_id                   int unsigned,
  piiri                      varchar(255),
  lippukunta                 varchar(255),
  puhelinnro                 varchar(255),
  sahkoposti                 varchar(255),
  osoite                     varchar(255),
  keskeyttanyt               int unsigned,
  constraint pk_Vartio primary key (numero)
) ;

-- rasti
create table rasti (
  id                         int unsigned auto_increment not null,
  nimi                       varchar(255) not null,
  pomo_id                    int unsigned,
  kisa_id                    int unsigned,
  constraint pk_Rasti primary key (id)
) ;

-- rastimiehet
create table rastimiehet (
  id                         int unsigned auto_increment not null,
  rasti_id                   int unsigned not null,
  tekia_id                   int unsigned not null,
  constraint pk_Rastimiehet primary key (id)
) ;

-- rasti_tehtava_liitos
create table rasti_tehtava_liitos (
  id                         int unsigned auto_increment not null,
  rasti_id                   int unsigned not null,
  tehtava_id                 int unsigned not null,
  constraint pk_Rasti_tehtava_liitos primary key (id)
) ;

-- raakatulos
create table raakatulos (
  id                         int unsigned auto_increment not null,
  aika                       float(4,2),
  numero                     float(4,2),
  boolean                    int unsigned,
  syottaja_id                int unsigned,
  constraint pk_Raakatulos primary key (id)
) ;

-- lopputulos
create table lopputulos (
  id                         int unsigned auto_increment not null,
  vartio_id                  int unsigned,
  tehtava_id                 int unsigned,
  rasti_id                   int unsigned,
  pisteet                    float(4,2),
  constraint pk_Lopputulos primary key (id)
) ;

-- syote
create table syote (
  id                         int unsigned auto_increment not null,
  nimi                       varchar(255) not null,
  tyyppi                     enum("aika","numero","boolean"),
  kayttoliittumavihje        varchar(255),
  constraint pk_Syote primary key (id)
) ;

-- arvosteluperuste
create table arvosteluperuste (
  id                         int unsigned auto_increment not null,
  pisteet                    float(4,2),
  constraint pk_Arvosteluperuste primary key (id)
) ;

-- osanottaja
create table osanottaja (
  id                         int unsigned auto_increment not null,
  nimi                       varchar(255) not null,
  syntumavuosi               int unsigned,
  lippukunta                 varchar(255),
  jasennumero                varchar(255),
  vartio_nro                 int unsigned,
  constraint pk_Osanottaja primary key (id)
) ;

-- allergia
create table allergia (
  id                         int unsigned auto_increment not null,
  mille                      varchar(255),
  osanottaja_id              int unsigned,
  constraint pk_Allergia primary key (id)
) ;

-- sarja_rasti_liitos
create table sarja_rasti_liitos (
  id                         int unsigned auto_increment not null,
  sarja_id                   int unsigned not null,
  rasti_id                   int unsigned not null,
  constraint pk_Sarja_rasti_liitos primary key (id)
) ;

-- rasti_vartio_liitos
create table rasti_vartio_liitos (
  id                         int unsigned auto_increment not null,
  rasti_id                   int unsigned not null,
  vartio_id                  int unsigned not null,
  constraint pk_Rasti_vartio_liitos primary key (id)
) ;


















-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Dec 21 12:04:42 2008
--     Input Files:       tietokanta.dia




-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Dec 21 12:04:42 2008
--     Input Files:       tietokanta.dia



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Dec 21 12:04:42 2008
--     Input Files:       tietokanta.dia



-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Dec 21 12:04:42 2008
--     Input Files:       tietokanta.dia


